---
title: "STA6714_Step2_Term_Project"
author: "Benjamin Garcia"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(readxl)
library(ggplot2)
features2 <- read_excel("features2.xlsx")

```



```{r }

table(features2$JJS, features2$Label)
table(features2$NNP)
table(features2$WRB)
table(features2$exclamationmarks, features2$Label)
#table(features2$questionmarks)
#table(features2$semicolon)
table(features2$ellipsis)
table(features2$TOs, features2$Label)

# can remove predictors JJS, NNP, WRB, exclamationmark, TOs, and ellipsis due to sparsity or all zeroes

```


```{r}
table(features2$sentence1st)
table(features2$sentencelast)

# can remove these as well
```


```{r}
feat3 <- features2[,-c(1, 2, 15, 19, 31, 42, 51, 60 , 61 )]

# removed TextID, URL, JJS, NNP, TOs, WRB, ellipsis, sentence1st, sentencelast 
```



```{r }
# Let 1 = objective and 0 = subjective

feat3$Label <- ifelse(feat3$Label == "objective", 1, 0)
table(feat3$Label)

```

```{r}
round(cor(feat3[,c(1,43:53)]), 2)

round(cor(feat3[,c(1:17)]), 2)

round(cor(feat3[,c(1,18:32)]), 2)

round(cor(feat3[,c(1,32:42)]), 2)

```

```{r}
library(reshape) 

cor.mat2 <- round(cor(feat3[,c(1:13)]), 2) 
melted.cor.mat2 <- melt(cor.mat2)
ggplot(melted.cor.mat2, aes(x=X1, y=X2, fill=value)) +
  geom_tile() + xlab("") + ylab("") + ggtitle("Heatmap for word and grammar predictors") +
  scale_fill_distiller(palette="RdBu", limits=c(-1, 1))
```


```{r}
head(feat3)
```

```{r}
# The following variables are being removed due to high correlation with other predictors

feat4 <- feat3[,-c(2,3,4,6,9,10,14,21,26,31,40,41,37,47,52)]


```


```{r}
#round(cor(feat4), 2) > .7

cor.mat3 <- round(cor(feat4[,]), 2) 
melted.cor.mat3 <- melt(cor.mat3)
ggplot(melted.cor.mat3, aes(x=X1, y=X2, fill=value)) +
  geom_tile() + xlab("") + ylab("") + ggtitle("Heatmap for word and grammar predictors") +
  scale_fill_distiller(palette="RdBu", limits=c(-1, 1))
```

```{r}
#additional removal due to correlation

feat5 <- feat4[,-c(5,7,9,12,13,17,18,19,20,21,22,29,34,36,37)]
```


```{r}
cor.mat4 <- round(cor(feat5[,]), 2) 
melted.cor.mat4 <- melt(cor.mat4)
ggplot(melted.cor.mat4, aes(x=X1, y=X2, fill=value)) +
  geom_tile() + xlab("") + ylab("") + ggtitle("Heatmap for word and grammar predictors") +
  scale_fill_distiller(palette="RdBu", limits=c(-1, 1))
```

```{r}
# exploratory data analysis

barplot(tapply(feat5$pronouns1st, feat5$Label, median), xlab = "Label",
        ylab = "Median first person pronouns", main = "Barplot of median first person pronouns for
      objective vs subjective", col = c("red", "blue"))
```


```{r}
g <- hist(feat5$Quotes, main = "Histogram of number of quotes used", 
          xlab = "Quotes", col = "brown")
text(g$mids,g$counts,labels=g$counts, adj=c(0.5, -0.5))

table(feat5$Quotes)

```


```{r}
ggplot(feat5, aes(as.factor(Label), txtcomplexity)) + geom_boxplot() + 
  labs(title = "Boxplots of text complexity by objective vs
        subjective", x = "Label") 
```


```{r}
ggplot(feat5, aes(x = NN, y = RB, color = as.factor(Label))) + geom_point() + 
  labs(title = "Frequency of Singular Nouns Against Adverb Colored by Target",
       x = "Singular Nouns", y = "Adverb")

```

```{r}
# scaling

feat5_scal <- cbind(feat5[,1], scale(feat5[,c(2:23)]))
```



```{r}

# full model
set.seed(7)

ind <- sample(1:1000, 700, replace = F)
train.df <- feat5_scal[ind,]
holdout.df <- feat5_scal[-ind,]

logmod1 <- glm(formula = Label ~., family = binomial(link = "logit"), data = train.df)

summary(logmod1)

```

```{r}
# Step-wise or bidirection regression applied to full model

step_mod_both <- MASS::stepAIC(
  object = logmod1,
  direction = "both"
)

step_mod_both
```


```{r}
anova(logmod1, step_mod_both, test = "Chisq")
```

```{r}
# predict

pred <- predict(step_mod_both, holdout.df[,2:23])

prob.predictions <- 1 / (1 + exp(-pred))
```



```{r}
# confusion matrix for .5

caret::confusionMatrix(factor(ifelse(prob.predictions > .5, 1, 0)), factor(holdout.df$Label))

```


```{r}
# confusion matrix for .25
caret::confusionMatrix(factor(ifelse(prob.predictions > .25, 1, 0)), factor(holdout.df$Label))

```


```{r}
# confusion matrix for .75

caret::confusionMatrix(factor(ifelse(prob.predictions > .75, 1, 0)), factor(holdout.df$Label))
```



```{r}
# ROC curve
library(ROCR)
predob <- prediction(ifelse(prob.predictions > .5, 1, 0), holdout.df$Label)
perf <- performance(predob, "tpr", "fpr")
perf.df <- data.frame(tpr = perf@x.values[[1]],
                      fpr = perf@y.values[[1]])
ggplot2::ggplot(perf.df, aes(x = tpr, y = fpr))+
  geom_line()+
  geom_segment(aes(x=0, y=0, xend=1, yend=1), color = "gray", linetype = "dashed")+
  labs(x = "1-Specificity", y = "Sensitivity")

performance(predob, measure = "auc")@y.values[[1]]

```

